stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'  # Используем vmImage вместо name
    steps:
    - checkout: self  # Явное указание checkout
      fetchDepth: 1
    
    - task: Docker@2
      displayName: 'Build and push'
      inputs:
        command: buildAndPush
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.Lab5.Web/Dockerfile'
        containerRegistry: 'Container Registry Connection'
        tags: $(tag)
        buildContext: $(Build.Repository.LocalPath)

- stage: 'Deploy'
  displayName: 'Deploy'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-20.04'  # Аналогичное исправление
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        appName: $(WebAppName)
        azureSubscription: 'Resource Manager - Tailspin - Lab5'
        imageName: $(RegistryName)/$(webRepository):$(build.buildId)