stages:
- stage: 'Build'
  displayName: 'Build the container'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - script: echo "Building the container..."
      displayName: 'Build step'

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build  # Указывает, что эта стадия зависит от стадии 'Build'
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
    - group: Release  # Использует переменные из группы 'Release'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        appName: $(WebAppName)
        azureSubscription: 'Resource Manager - Tailspin - Lab5'
        imageName: $(RegistryName)/$(webRepository):$(build.buildId)